"""strategy logs + run state

Revision ID: 868520bb57a2
Revises: 15223181f90a
Create Date: 2026-06-07 13:08:29.231390
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '868520bb57a2'
down_revision: Union[str, None] = '15223181f90a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('internal_symbol', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_logs_run_id'), 'strategy_logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_strategy_logs_strategy_id'), 'strategy_logs', ['strategy_id'], unique=False)
    op.add_column('strategy_runs', sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy_runs', 'state')
    op.drop_index(op.f('ix_strategy_logs_strategy_id'), table_name='strategy_logs')
    op.drop_index(op.f('ix_strategy_logs_run_id'), table_name='strategy_logs')
    op.drop_table('strategy_logs')
    # ### end Alembic commands ###
