"""strategies crud, runs, triggers, backtests

Revision ID: 8a041f43590d
Revises: ffdca50290d4
Create Date: 2026-06-07 07:34:03.401440
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8a041f43590d'
down_revision: Union[str, None] = 'ffdca50290d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('capital', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_user_id'), 'backtests', ['user_id'], unique=False)
    op.create_table('triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.String(), nullable=True),
    sa.Column('strategy_run_id', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('internal_symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('limit_timeout_sec', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_ltp', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_internal_symbol'), 'triggers', ['internal_symbol'], unique=False)
    op.create_index(op.f('ix_triggers_state'), 'triggers', ['state'], unique=False)
    op.create_index(op.f('ix_triggers_user_id'), 'triggers', ['user_id'], unique=False)
    op.create_table('strategy_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_runs_strategy_id'), 'strategy_runs', ['strategy_id'], unique=False)
    op.add_column('strategies', sa.Column('status', sa.String(), nullable=False))
    op.add_column('strategies', sa.Column('symbols', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('strategies', sa.Column('timeframe_min', sa.Integer(), nullable=True))
    op.add_column('strategies', sa.Column('capital', sa.Numeric(precision=20, scale=2), nullable=False))
    op.add_column('strategies', sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('strategies', sa.Column('code', sa.Text(), nullable=True))
    op.add_column('strategies', sa.Column('risk', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('strategies', sa.Column('auto_start_on_login', sa.Boolean(), nullable=False))
    op.add_column('strategies', sa.Column('auto_start_broker_account_id', sa.String(), nullable=True))
    op.add_column('strategies', sa.Column('auto_start_is_paper', sa.Boolean(), nullable=False))
    op.add_column('strategies', sa.Column('preferred_broker_account_ids', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'preferred_broker_account_ids')
    op.drop_column('strategies', 'auto_start_is_paper')
    op.drop_column('strategies', 'auto_start_broker_account_id')
    op.drop_column('strategies', 'auto_start_on_login')
    op.drop_column('strategies', 'risk')
    op.drop_column('strategies', 'code')
    op.drop_column('strategies', 'definition')
    op.drop_column('strategies', 'capital')
    op.drop_column('strategies', 'timeframe_min')
    op.drop_column('strategies', 'symbols')
    op.drop_column('strategies', 'status')
    op.drop_index(op.f('ix_strategy_runs_strategy_id'), table_name='strategy_runs')
    op.drop_table('strategy_runs')
    op.drop_index(op.f('ix_triggers_user_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_state'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_internal_symbol'), table_name='triggers')
    op.drop_table('triggers')
    op.drop_index(op.f('ix_backtests_user_id'), table_name='backtests')
    op.drop_table('backtests')
    # ### end Alembic commands ###
