"""broker account session fields

Revision ID: ffdca50290d4
Revises: 69f8aa9f5ced
Create Date: 2026-06-07 07:08:30.254021
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ffdca50290d4'
down_revision: Union[str, None] = '69f8aa9f5ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_accounts', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('broker_accounts', sa.Column('label', sa.String(), nullable=True))
    op.add_column('broker_accounts', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('broker_accounts', sa.Column('session_valid_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('broker_accounts', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('broker_accounts', sa.Column('last_error', sa.Text(), nullable=True))
    op.alter_column('roles', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'id',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('broker_accounts', 'last_error')
    op.drop_column('broker_accounts', 'last_login_at')
    op.drop_column('broker_accounts', 'session_valid_until')
    op.drop_column('broker_accounts', 'is_active')
    op.drop_column('broker_accounts', 'label')
    op.drop_column('broker_accounts', 'client_id')
    # ### end Alembic commands ###
